---
- name: 'Install lldap and tools'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.install_one_or_more_packages'
      packages_to_be_installed:
        - lldap
        - lldap-set-password
        - lldap-migration-tool
        - lldap-cli
